# Generated by Django 5.0.14 on 2026-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('home', "Bandeau page d'accueil"), ('sidebar', 'Sidebar des articles'), ('article', 'Bas de page article')], max_length=20),
        ),
    ]
