# Generated by Django 5.0.14 on 2026-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='emissions/')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Animateur(s)')),
                ('video_url', models.URLField(blank=True, verbose_name='Lien vidéo / replay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Émission',
                'verbose_name_plural': 'Émissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
