# Generated by Django 5.0.14 on 2026-07-23 07:49

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='emissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size]),
        ),
    ]
